---
title: "Poor Man's 538"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(jsonlite)
library(xts)
library(zoo)
library(dygraphs)
library(lubridate)
library(ggplot2)

# Get API data
historicalURL <- 'https://projects.fivethirtyeight.com/trump-approval-ratings/historical-approval.json'
trumpURL      <- 'https://projects.fivethirtyeight.com/trump-approval-ratings/approval.json'
tableURL      <- 'https://projects.fivethirtyeight.com/trump-approval-ratings/polls.json'

approvalRatings <- fromJSON(historicalURL)
trumpApproval   <- fromJSON(trumpURL)
tableData       <- fromJSON(tableURL)
```

Row {data-width=650}
-----------------------------------------------------------------------

### How popular/unpopular is Trump?

```{r}
trumpApproval <- subset(trumpApproval, 
                        trumpApproval$subgroup == 'All polls' & 
                          trumpApproval$future == F)
disapprove <- ts(trumpApproval$disapprove_estimate, 
                 start = c(2017, 23), 
                 frequency = 365)
approve    <- ts(trumpApproval$approve_estimate, start = c(2017, 23), 
                 frequency = 365)

ratings <- cbind(disapprove, approve)
ratings <- as.zoo(ratings)
ratings <- as.xts(ratings, date_decimal(index(ratings)))

dygraph(ratings, "Trump Approval") %>%
  dySeries("approve", label = "approve", color = 'green') %>%
  dySeries("disapprove", label = "disapprove", color = 'red') %>%
  dyRangeSelector()

```

Row {data-width=350}
-----------------------------------------------------------------------

### All Polls

```{r}
DT::datatable(tableData, 
              options = list(bPaginate = TRUE))
```

Row {data-width=350}
-----------------------------------------------------------------------

### How Trump compares with past presidents: Bush

```{r}
approvalSub<- approvalRatings[grepl('George W. Bush|Barack Obama',
                                approvalRatings$president),]
approvalSub$date <- ymd(approvalSub$date)

bush  <- subset(approvalSub, approvalSub$president=='George W. Bush')
obama <- subset(approvalSub, approvalSub$president=='Barack Obama')
plot(bush$date, bush$approve_estimate, type = 'l', col= 'blue')
lines(bush$date, bush$disapprove_estimate, col='red')

```

### How Trump compares with past presidents: Obama

```{r}
approvalSub<- approvalRatings[grepl('George W. Bush|Barack Obama',
                                approvalRatings$president),]
approvalSub$date <- ymd(approvalSub$date)

bush  <- subset(approvalSub, approvalSub$president=='George W. Bush')
obama <- subset(approvalSub, approvalSub$president=='Barack Obama')
plot(obama$date, obama$approve_estimate, type = 'l', col= 'blue')
lines(obama$date, obama$disapprove_estimate, col='red')
```